pool:
  name: Default
  demands:
  - msbuild
  - vstest

trigger:
- master
- develop
- release/*
- hotfix/*
- feature/*

variables:
  AssemblyVersion: '1.0'
  Solution: 'src/TestWebApp.sln'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  SkipTests: false

steps:
- task: GitVersion@1
  displayName: 'GitVersion '
  inputs:
    BuildNamePrefix: SampleAspNetForDeploy

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Solution)'

- task: FileTransform@1
  displayName: 'File Transform: '
  inputs:
    folderPath: src/TestWebApp/
    enableXmlTransform: true
    xmlTransformationRules: '-transform web.$(BuildConfiguration).config -xml web.config'
    fileType: xml

- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    solution: '$(Solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:OutDir="." /p:Configuration=$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/WebApp'
  inputs:
    SourceFolder: 'src/TestWebApp/_PublishedWebsites/TestWebApp'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/WebApp'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApp'
    ArtifactName: WebApp
  condition: succeededOrFailed()
